version: "3.8"

services:
  alterego:
    image: ghcr.io/flufflesamy/alterego-docker:latest
    container_name: alterego
    volumes:
      # Bind mounts for configuration files
      - ./config/credentials.json:/app/Alter-Ego/credentials.json
      - ./config/game.json:/app/Alter-Ego/game.json
      - ./config/settings.json:/app/Alter-Ego/settings.json
    restart: unless-stopped